{{- if .Values.auditScanner.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "audit-scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "kubewarden-controller.annotations" . | nindent 4 }}
spec:
  schedule: {{ .Values.auditScanner.cronJob.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ .Values.auditScanner.cronJob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.auditScanner.cronJob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.auditScanner.serviceAccountName }}
          {{- with .Values.podSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- include "imagePullSecrets" .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.auditScanner.containerRestartPolicy }}
          volumes:
          - name: policyservers-ca-cert
            secret:
              defaultMode: 420
              secretName: policy-server-root-ca
              items:
              - key: policy-server-root-ca-pem
                path: "policy-server-root-ca-pem"
          containers:
          - name: audit-scanner
            image: '{{ template "system_default_registry" . }}{{ .Values.auditScanner.image.repository }}:{{ .Values.auditScanner.image.tag }}'
            imagePullPolicy: {{ .Values.auditScanner.image.pullPolicy }}
            command:
              {{- include "audit-scanner.command" . | nindent 14 -}}
            {{- with .Values.containerSecurityContext }}
            volumeMounts:
            - mountPath: "/pki"
              name: policyservers-ca-cert
              readOnly: true
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.affinity }}
            affinity:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.tolerations }}
            tolerations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if and .Values.resources .Values.resources.auditScanner }}
            resources:
{{ toYaml .Values.resources.auditScanner | indent 14 }}
            {{- end }}
{{ end }}
