# In some scenarios when telemetry is enabled, due some concurrency issues,
# when the OTEL operator try to inject the collector container in the controller
# pod, it cannot find a valid collector configuration. Therefore, it is necessary
# to recreate the controller pod after the installation. This ensures that the
# controller pod will have the OTEL collector container.
{{ if or .Values.telemetry.metrics.enabled .Values.telemetry.tracing.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-delete-controller-job"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- include "kubewarden-controller.annotations" . | nindent 4 }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-delete-controller-job"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      annotations:
        {{- include "kubewarden-controller.annotations" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "kubewarden-controller.serviceAccountName" . }}
      {{- if .Values.preDeleteHook.podSecurityContext }}
      securityContext:
{{ toYaml .Values.preDeleteHook.podSecurityContext | indent 8 }}
      {{- end }}
      containers:
        - name: post-install-job
          image: '{{ template "system_default_registry" . }}{{ .Values.preDeleteJob.image.repository }}:{{ .Values.preDeleteJob.image.tag }}'
          command: ["kubectl", "--namespace", "{{ .Release.Namespace }}", "rollout", "restart", "deployment", {{ include "kubewarden-controller.fullname" . }}]
          {{- if .Values.preDeleteHook.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.preDeleteHook.containerSecurityContext | indent 12 }}
          {{- end }}
{{ end }}
