apiVersion: v2
name: kubewarden-crds
description: A Helm chart for deploying the Kubewarden CRDs
icon: https://www.kubewarden.io/images/icon-kubewarden.svg
type: application
kubeVersion: ">= 1.19.0"
home: https://www.kubewarden.io/
maintainers:
- name: Flavio Castelli
  email: fcastelli@suse.com
- name: Rafael Fernández López
  email: rfernandezlopez@suse.com
- name: Victor Cuadrado Juan
  email: vcuadradojuan@suse.com
- name: Jose Guilherme Vanz
  email: jguilhermevanz@suse.com
- name: Raul Cabello Martin
  email: raul.cabello@suse.com
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.0
