apiVersion: v2
name: kubewarden-crds
description: A Helm chart for deploying the Kubewarden CRDs
icon: https://www.kubewarden.io/images/icon-kubewarden.svg
type: application
kubeVersion: ">= 1.19.0"
home: https://www.kubewarden.io/
maintainers:
- name: Flavio Castelli
  email: fcastelli@suse.com
- name: Rafael Fernández López
  email: rfernandezlopez@suse.com
- name: Victor Cuadrado Juan
  email: vcuadradojuan@suse.com
- name: Jose Guilherme Vanz
  email: jguilhermevanz@suse.com
- name: Raul Cabello Martin
  email: raul.cabello@suse.com
keywords:
  - Security
  - Infrastructure
  - Monitoring

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.0

annotations:
  # required ones:
  catalog.cattle.io/certified: rancher # Any application we are adding as a helm chart
  catalog.cattle.io/namespace: cattle-kubewarden-system # Must prefix with cattle- and suffix with -system
  catalog.cattle.io/release-name: rancher-kubewarden-crds # If this is an upstream app, prefixing with rancher is the preferred naming choice.
  catalog.cattle.io/os: linux   # this means linux only, other choice here is "windows". For charts that support both, don't add this annotation

  # optional ones:
  catalog.cattle.io/hidden: true  # Hide specific charts. Only use on CRD charts.

  catalog.cattle.io/scope: management # Chart is only applicable to the management/local cluster and will be only shown as an option for the local cluster
  # Valid values for the following annotation include: `cluster-tool`, `app` or `cluster-template`
  # See the Cluster Tools section to learn more about when to set this value to `cluster-tool`.
  catalog.cattle.io/type: cluster-tool
