apiVersion: v2
name: kubewarden-defaults
description: A Helm chart for deploying Kubewarden's default PolicyServer instance
icon: https://www.kubewarden.io/images/icon-kubewarden.svg
type: application
kubeVersion: ">= 1.19.0"
home: https://www.kubewarden.io/
maintainers:
- name: Jos√© Guilherme Vanz
  email: jguilhermevanz@suse.com
keywords:
  - Security
  - Infrastructure
  - Monitoring

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.7

annotations:
  # required ones:
  catalog.cattle.io/certified: rancher # Any application we are adding as a helm chart
  catalog.cattle.io/namespace: cattle-kubewarden-system # Must prefix with cattle- and suffix with -system
  catalog.cattle.io/release-name: rancher-kubewarden-defaults # If this is an upstream app, prefixing with rancher is the preferred naming choice.
  catalog.cattle.io/ui-component: kubewarden # This is added for custom UI deployment of a chart
  catalog.cattle.io/display-name: Kubewarden-defaults # Only for Charts with custom UI
  catalog.cattle.io/os: linux   # this means linux only, other choice here is "windows". For charts that support both, don't add this annotation

  # optional ones:
  catalog.cattle.io/requires-gvr: "policyservers.policies.kubewarden.io/v1" # This type MUST be visible to the user before they can install this chart.

  catalog.cattle.io/scope: management # Chart is only applicable to the management/local cluster and will be only shown as an option for the local cluster
  # Valid values for the following annotation include: `cluster-tool`, `app` or `cluster-template`
  # See the Cluster Tools section to learn more about when to set this value to `cluster-tool`.
  catalog.cattle.io/type: cluster-tool
