{{ if .Values.recommendedPolicies.enabled }}
apiVersion: {{ $.Values.crdVersion }}
kind: ClusterAdmissionPolicy
metadata:
  labels:
    {{- include "kubewarden-defaults.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy
  annotations:
    io.kubewarden.policy.category: PSP
    io.kubewarden.policy.severity: medium
    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
  name: {{ $.Values.recommendedPolicies.capabilitiesPolicy.name }}
spec:
  mode: {{ $.Values.recommendedPolicies.defaultPolicyMode }}
  module: {{ template "policy_default_registry" . }}{{ .Values.recommendedPolicies.capabilitiesPolicy.module.repository }}:{{ .Values.recommendedPolicies.capabilitiesPolicy.module.tag }}
{{ include "policy-namespace-selector" . | indent 2}}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
{{- if .Values.recommendedPolicies.capabilitiesPolicy.allowed_capabilities }}
      allowed_capabilities:
      {{- range .Values.recommendedPolicies.capabilitiesPolicy.allowed_capabilities }}
        - {{ . }}
      {{- end }}
{{- end }}
{{- if .Values.recommendedPolicies.capabilitiesPolicy.required_drop_capabilities }}
      required_drop_capabilities:
      {{- range .Values.recommendedPolicies.capabilitiesPolicy.required_drop_capabilities }}
        - {{ . }}
      {{- end }}
{{- end }}
{{- if .Values.recommendedPolicies.capabilitiesPolicy.default_add_capabilities }}
      default_add_capabilities:
      {{- range .Values.recommendedPolicies.capabilitiesPolicy.default_add_capabilities }}
        - {{ . }}
      {{- end }}
{{- end }}
{{ end }}
