{{ if .Values.recommendedPolicies.enabled }}
apiVersion: {{ $.Values.crdVersion }}
kind: ClusterAdmissionPolicy
metadata:
  labels:
    {{- include "kubewarden-defaults.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy
  name: {{ $.Values.recommendedPolicies.hostPathsPolicy.name }}
spec:
  mode: {{ $.Values.recommendedPolicies.defaultPolicyMode }}
  module: '{{ template "system_default_registry" . }}{{ $.Values.recommendedPolicies.hostPathsPolicy.module }}'
{{ include "policy-namespace-selector" . | indent 2}}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
  settings:
    allowedHostPaths:
{{- range .Values.recommendedPolicies.hostPathsPolicy.paths }}
    - pathPrefix:  {{ .pathPrefix | quote }}
      readOnly: {{ .readOnly  }}
{{- end }}
{{ end }}
