{{ if .Values.recommendedPolicies.enabled }}
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: {{ $.Values.recommendedPolicies.userGroupPolicy.name }}
spec:
  policyServer: {{ $.Values.policyServer.name }}
  mode: {{ $.Values.recommendedPolicies.defaultPolicyMode }}
  module: {{ $.Values.recommendedPolicies.userGroupPolicy.module }}
{{ include "policy-namespace-selector" . | indent 2}}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    run_as_user:
      rule: "MustRunAsNonRoot"
    run_as_group:
      rule: "RunAsAny"
    supplemental_groups:
      rule: "RunAsAny"
{{ end }}
