---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "sbomscanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ include "sbomscanner.fullname" . }}-controller
rules:
- apiGroups:
  - sbomscanner.kubewarden.io
  resources:
  - registries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sbomscanner.kubewarden.io
  resources:
  - scanjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sbomscanner.kubewarden.io
  resources:
  - scanjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.sbomscanner.kubewarden.io
  resources:
  - vulnerabilityreports
  verbs:
  - get
  - list
  - watch
