name: Sync SBOMscanner Helm chart

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release-sbomscanner]

jobs:
  sync-sbomscanner:
    name: Sync SBOMscanner Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@4b17f4ea784de29f71f85f9bc4955402ba1ae53c # v2.100.0

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update SBOMscanner helm chart
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: |-
          updatecli compose apply --file ./updatecli/sbomscanner-release.yaml
