name: Sync SBOMscanner Helm chart

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release-sbomscanner]
  schedule:
    - cron: "30 3 * * 1" # 3:30 on Monday

jobs:
  sync-sbomscanner:
    name: Sync SBOMscanner Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@719e3592d124cbf826da704cbe557e1221dd4bba # v2.94.0

      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update SBOMscanner helm chart
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: |-
          updatecli compose apply --file ./updatecli/sbomscanner-release.yaml
